### PR TITLE
Properly quote column names in CREATE TABLE query.

### LINKED ISSUE #53: Not quoted column names in `CREATE TABLE` query
Scylla Sink Connector provides the functionality to automatically create Scylla table based on Kafka message schema.

However, the generated `CREATE TABLE` query does not correctly quote column names (for example if you have a column name `one two three` with spaces you must write it in quotes `"one two three"` - `quoteIfNecessary` method in Java Driver).

Reproducer:

1. Scylla (cqlsh): `CREATE KEYSPACE ks WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1};`
2. In Kafka create a `mytable` topic.
3. Start the connector with the following configuration:
    ```
    {
      "key.converter.schemas.enable": "true",
      "value.converter.schemas.enable": "true",
      "name": "mytableConnector",
      "connector.class": "io.connect.scylladb.ScyllaDbSinkConnector",
      "key.converter": "org.apache.kafka.connect.json.JsonConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "topics": [
        "mytable"
      ],
      "scylladb.contact.points": "127.0.0.2",
      "scylladb.port": "9042",
      "scylladb.keyspace": "ks"
    }
    ```
4. Write the message to Kafka using console producer (columns that show the issue: `primary key` and `ck!@#$%^&*()`): 
    ```
    $ bin/kafka-console-producer --topic mytable --bootstrap-server localhost:9092 --property parse.key=true --property "key.separator=?"
    {"schema": {"type": "struct", "fields": [{"type": "int64", "optional": false, "field": "primary key"}, {"type": "int64", "optional": false, "field": "ck!@#$%^&*()"} ], "optional": false, "name": "mytablePK"}, "payload": {"primary key": 5, "ck!@#$%^&*()": 10}}?{"schema": {"type": "struct", "fields": [{"type": "int64", "optional": false, "field": "primary key"}, {"type": "int64", "optional": false, "field": "ck!@#$%^&*()"}, {"type": "int64", "optional": false, "field": "v"} ], "optional": false, "name": "mytableVAL"}, "payload": {"primary key": 5, "ck!@#$%^&*()": 10, "v": 15}} 
    ```
5. The connector fails. In the logs (`/tmp/confluent.XXXXXX/connect/logs/connect.log` in case of Confluent) you can see:
    ```
    CREATE TABLE ks.mytable(
               primary key bigint,
               ck!@#$%^&*() bigint,
               v bigint,
               PRIMARY KEY((primary key, ck!@#$%^&*())))
    ```
    The correct query should be: 
    ```
    CREATE TABLE ks.mytable (
              "primary key" bigint, 
              "ck!@#$%^&*()" bigint, 
              v bigint, 
              PRIMARY KEY("primary key", "ck!@#$%^&*()"));
    ```

### PR DESCRIPTION
**Pull request by Lorak-mmk**
Columns names passed to CREATE TABLE statement sometimes need to be quoted, and Java driver 3.x doesn't do it automatically.

Fixes #53

### CODE REVIEW

**Comment by haaawk** [comment]
LGTM but what about the following places - don't we have to fix them as well?

https://github.com/scylladb/kafka-connect-scylladb/blob/9d77875bfc24a3138407a38d704b7b224c1f5b9f/src/main/java/io/connect/scylladb/ScyllaDbSchemaBuilder.java#L182

https://github.com/scylladb/kafka-connect-scylladb/blob/9d77875bfc24a3138407a38d704b7b224c1f5b9f/src/main/java/io/connect/scylladb/ScyllaDbSchemaBuilder.java#L199

https://github.com/scylladb/kafka-connect-scylladb/blob/9d77875bfc24a3138407a38d704b7b224c1f5b9f/src/main/java/io/connect/scylladb/ScyllaDbSchemaBuilder.java#L216

They are ALTER related so not strictly in scope of the issue #53 but maybe it's worth fixing them as well since you're at this matter?

**Comment by avelanarius** [comment]
A small nit: the commit message is a single line: "Properly quote column names in CREATE TABLE query. Fixes issue #53". The convention we stick to is: 
1. Subject line (first line) - 50 character limit, no `.` at the end.
2. Blank line (so that the subject line and body are separated).
3. Body - 72 character per line limit (72 character wrapping).

You also probably should have included "Columns names passed to CREATE TABLE statement sometimes need to be quoted, and Java driver 3.x doesn't do it automatically." in a commit message body (not only PR description).

On a positive side: it's great you remembered to put "Fixes #..." in the description. Remember to be careful, as "Fixes issue #..." does not automatically close the issue, while "Fixes #..." does.

**Comment by Lorak-mmk** [comment]
> They are ALTER related so not strictly in scope of the issue #53 but maybe it's worth fixing them as well since you're at this matter?

Sure. I fixed those places now too @haaawk.

I also rewrote commit message to fit the convention @avelanarius.

**Review by haaawk — APPROVED** [review]
LGTM - I will leave it to @avelanarius to merge

**Pull request merged**
